### ISSUE TITLE
add support for asn type DATE

### ISSUE THREAD

**Issue by AMCON-Chenet** [librasn/compiler#27]
Hello,

is it possible to support the ASN1-type DATE?
I have a sequence like this and can't generate code with the rasn-compiler.

```
common DEFINITIONS IMPLICIT TAGS ::=
BEGIN
EXPORTS ALL;
     Subject ::= [1] SEQUENCE {
         subjectName [1] UTF8String OPTIONAL,
         -- YYYY-MM-DD
         dateOfBirth [2] DATE OPTIONAL
    }
END
```

**Comment by 6d7a** [comment]
Thank you for your issue. Currently the `rasn` framework does not support the `DATE` type, so the compiler does neither. Please feel free to open an issue [here](https://github.com/librasn/rasn/issues) to request `DATE` support in `rasn`. Also, PRs are always welcome in case you want to contribute.
As far as your example is concerned, the tags make me assume you are using BER, CER, or DER as encoding rules. As a dirty workaround, you could try changing the `DATE` type to `UTF8String`, since BER, CER, and DER encode `DATE`s as UTF8 strings, if I'm not mistaken.
